step6-2 mukeunzi
code-squad/javascript-json pull request #207
Opened 2019-05-17 05:56 UTC by mukeunzi

step6-2 리뷰 부탁드립니다!!!!!!

2019-05-17 07:04 UTC, honux77 commented on array_parser.js
> +	tokenizer(inputStr) {
너무 길어요. 작은 함수로 나눠 보세요.

2019-05-17 07:06 UTC, honux77 commented on array_parser.js
> +					if (makeStr !== '') {
4단계 들여쓰기 ㅜㅜ. 이것도 줄여 보세요.

2019-05-17 07:07 UTC, honux77 commented on array_parser.js
> +	getTypeAndValue(token) {
이것도 조금 긴데요. 가능하면 좀 나눠 보세요.

2019-05-17 07:08 UTC, honux77 requested changes
if else 가 너무 많아요. 
불필요한 if else 를 줄이고
길이가 긴 함수는 작은 함수로 나눠 보세요.

2019-05-19 11:16 UTC, mukeunzi commented
> step6-2 리뷰 부탁드립니다!!!!!!

길이가 긴 함수 작은 함수로 나눈 후 다시 PR 보냅니다..!

2019-05-27 06:15 UTC, honux77 commented
아직도 약간 맘에 들지 않지만 '이 정도면 됐겠지' 라는 마음으로 승인합니다. 다른 분들 코드도 꼭 보고 비교해 보세요.

2019-05-27 06:15 UTC, merged

2019-05-27 07:19 UTC, mukeunzi commented
네..! 비교해보겠습니다.
감사합니다!