sage Step6-2 구현
code-squad/javascript-json pull request #209
Opened 2019-05-17 17:28 UTC by lionho

master로 보낸 pr 닫고 다시 요청드립니다.

2019-05-20 04:06 UTC, crongro requested changes
앙꼬같은 구현코드입니다.

부탁드린  것을 추가해주세요.!

2019-05-20 04:06 UTC, crongro commented on arrayparser_class.js
> +const Node = require('./node_class.js');
파일이름은, 
class 형태라고 해서 class라고 이름짓지 말고요. 
의미만 표현하도록 하세요. arrayParser.js 라고 하는 것이 낫겠어요.

2019-05-20 04:06 UTC, nigayo commented on arrayparser_class.js
> +    parse(lexer) {
parse 의 동작을 시각화된 방법으로 (종이를 사용해도 좋고요, 칠판에 표현한걸 찍어도 좋고요)
표현해서 commit/push 해주세요.

이해를 확실히 하고 넘어가면 좋겠습니다.

2019-05-20 23:50 UTC, lionho commented
수정사항 반영했습니다.

2019-05-21 06:16 UTC, nigayo commented
PR 충돌이 있네요.

그리고, 
설계문서를 사진으로  추가하셨는데요, 시간될때 parser부분의 동작을 markdown으로 정리해보시면 더 좋을 거 같아요.

2019-05-21 06:55 UTC, lionho commented
일단 충돌은 해결했습니다.

2019-05-27 07:32 UTC, crongro approved these changes
늦게 확인했네요.
readme 에 정리한 내용 봤어요. stack으로 동작하는 parser방식에 대해서  술술 설명하실 수 있기를 바랄게요.
다른 문제들도 풀어보면 좋고요. 비슷한 문제들이 찾아보면 많아요.

2019-05-27 07:32 UTC, merged